package JavaApp;
public class App {
    //Do not edit this file ---------------------------------------------------
    public static void main(String[] args) throws Exception {
        //Create test data
        Location ipswich = new Location("Ipswich", null);
        Location norwich = new Location("Norwich", null);
        Location lowerstoft = new Location("Lowerstoft", null);
        Location rendlesham = new Location("Rendlesham", null);
        Location wickhammarket = new Location("Wickham Market", null);
        
        Location woodbridge = new Location("Woodbridge", new Location[] {rendlesham, wickhammarket});

        Location suffolk = new Location("Suffolk", new Location[] {ipswich, lowerstoft, woodbridge});
        Location norfolk = new Location("Norfolk", new Location[] {norwich});

        Location england = new Location("England", new Location[] {suffolk, norfolk});

        Location uk = new Location("UK", new Location[] {england});

        Print.PrintOutTree(uk);

        //Wait for enter to exit
        System.in.read();
    }
    //-------------------------------------------------------------------------
}
