package JavaApp;

//Do Not Edit This File ------------------------------------------------------------------
public class Location {
    private String name;
    private Location[] locations;

    public Location(String locationName, Location[] childLocations) {
        name = locationName;
        locations = childLocations;
    }

    public String getName() {
        return name;
    }

    public Location[] getLocations() {
        return locations;
    }
}
//--------------------------------------------------------------------------------------