# Do not edit this file
class Location:
    def __init__(self, locationName, children = None):
        self.name = locationName
        if children != None:
            self.locations = children

    name = ""
    locations = []